# Generated by Django 4.2.2 on 2025-10-19 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": [("can_manage_users", "Управление пользователем")],
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.AddField(
            model_name="user",
            name="country",
            field=models.CharField(
                blank=True,
                default="Неизвестно",
                max_length=20,
                null=True,
                verbose_name="страна проживания",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="token",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Токен для подтвержения почты",
            ),
        ),
    ]
